Rebase libxml branch, update arabica and fix packaging
cim-iec/libcimpp pull request #29
Opened 2024-10-29 23:53 UTC by tom-hg57

2024-11-16 12:16 UTC, m-mirz commented
@tom-hg57 a description would be nice.

2024-11-24 11:34 UTC, m-mirz requested changes

2024-11-24 11:34 UTC, m-mirz commented on arabica/CMakeLists.txt
> -  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}/static
@tom-hg57 is it not nicer to keep the variables here instead of hard coded paths? The old code looks more platform independent.

2024-11-24 11:49 UTC, tom-hg57 commented on arabica/CMakeLists.txt
> -  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}/static
Sure. But cpack didn't work with that. At least in my environment.
Please try, if it works for you with the variables. Then we could change it back.

2024-11-24 18:04 UTC, tom-hg57 commented on arabica/CMakeLists.txt
> -  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}/static
Fixed

2024-12-06 17:52 UTC, m-mirz approved these changes

2024-12-06 17:53 UTC, merged